# Lang
language: en

# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: Elsa
description: Architecture student, Web developer, ACG enthusiast. Interested in the interactions between human and everything else. Keep Learning and Exploring.
links:
  Blog: /archives
  GitHub: https://github.com/ElsaXing
  Email: mailto:elsaxingmiao@gmail.com
  About: /about




# Info
archive_footer_content: This is my Instrumentality Project. I am trying to record my life here. You can check my **[explorations](/categories/explore)** on different things, my **[project](/categories/project)**  or some **[game reviews](/categories/game)**, also if you are interested in my **[life](/categories/life)**.
post_footer_content: This is my Instrumentality Project. I am trying to record my life here. You can check my **[explorations](/categories/explore)** on different things, my **[project](/categories/project)**  or some **[game reviews](/categories/game)**, also if you are interested in my **[life](/categories/life)**.
